### ISSUE TITLE
Where, oh where, has our maintainer gone?

### ISSUE THREAD

**Issue by catb0t** [exercism/xfactor#15]
I'm not sure if I did something to irritate @kytrinyx, or if they have merely forgotten this repo exists (as it seems they have activity elsewhere on github) and missed notifications about it...?

Come baaack, we (I) need you to merge my pull(s)! D:

**Comment by kytrinyx** [comment]
Hi! Sorry—I've been swamped and totally lost track of all of this. I'll take a look!

**Comment by kytrinyx** [comment]
So, update: I'm watching the repository, but didn't get any notifications because GitHub only notifies me on PRs if

- it's new
- it gets closed or merged
- there's a comment

If you add code to a pull request (or force push), I don't get notified :/

**Comment by catb0t** [comment]
That's weird. You should poke someone at GH to fix that, maybe :)

**Comment by kytrinyx** [comment]
Haha, yeah, I should (and have). :)
