### ISSUE TITLE
What happened to the documentation?

### ISSUE THREAD

**Issue by catb0t** [exercism/xfactor#17]
I've been busy with school all summer and now I'm less busy. Did something about how the documentation is rendered change without my noticing? 

The files are all there in `docs` like they're supposed to be, yet none of them actually appear on http://exercism.io/languages/factor.

**Comment by catb0t** [comment]
Oh, it looks like none of the languages classed "Upcoming" or "Planned" show their docs on the site. Bug, I should think. @kytrinyx maybe this is already open on https://github.com/exercism/exercism.io.

**Comment by kytrinyx** [comment]
This is fixed! Thanks for reporting it.
