### ISSUE TITLE
Factor is very picky about filenames

### ISSUE THREAD

**Issue by catb0t** [exercism/xfactor#5]
Suppose we have this tree of exercises:
```
├── exercises
    ├── hello-world
    │   ├── example.factor              -- reference implementation
    │   ├── hello-world.factor          -- stub
    │   └── hello-world-tests.factor    -- unit tests
    └── leap
        ├── example.factor              -- reference implementation
        └── leap-tests.factor           -- unit tests
```
and suppose we say `USE: leap` (the equivalent of `import leap`, `require('leap')`, `using Leap;`, etc). 

Factor looks at `xfactor/exercises/leap` (after its other search paths) for a file called `leap.factor`, the implementation. For tests, Factor wants a file called `leap-tests.factor`, which is fine on both the github side and the client / user side.

Factor will completely ignore files not called `leap*.factor` when it is looking to load the `leap` vocabulary. Reference implementations must, as far as I can tell, be named `example`, or else they might get shipped off to the user, but in order for the exercise to run in CI or from git, the implementations must be named `exercise-name.factor`.

This is a fairly large problem if collaborators are to seamlessly write, run and commit / CI new exercises.

What can we do to resolve this? I'll talk to the Factor developers to see if they have suggestions, but I don't think they will be able to suggest much.

**Comment by kytrinyx** [comment]
As long as there's `example` in the filename it won't get shipped off to users, so `leap-example.factor` would work just fine.

**Comment by catb0t** [comment]
No dice; the filename of the implementation has to be `leap.factor`.

**Comment by catb0t** [comment]
Okay, I guess I've come up with exactly what I did not think would work. There's a different problem, now: Factor already has a vocabulary (aka module / library) named `hello-world` in its standard library, but everything here in Exercism has to be named with the slug `hello-world`. Unit tests referencing `hello-world` will try to import the standard library's version, not the user's / ours. But at least this is solved (mostly).

**Comment by kytrinyx** [comment]
Hey! Sorry it took me so long to get back to you. Yeah, we have make files that do exactly this in the ruby track, and the javascript tracks, and maybe also the elixir track.

https://github.com/exercism/xruby/blob/master/Makefile

**Comment by catb0t** [comment]
> Sorry it took me so long to get back to you.

No worries, I understand you're a busy human. :)

Why write it in Make when you can [write it in Factor](https://github.com/catb0t/xfactor/commit/243f674f7a52e909bb8e0bf81761778abeaa238d), and have built-in docs and unit-tests? :D (Unless you don't know Factor, but then you should learn it.)

**Comment by kytrinyx** [comment]
Writing it in factor is way better, of course! Duh :)
